import type { TestQuestion } from "@/components/TestMode";

export const enemVestibularQuestions: TestQuestion[] = [
  {
    id: "soma-1",
    category: "Soma e Subtração",
    difficulty: "básico",
    question: "Uma pessoa sai para dar um passeio pela cidade, fazendo o seguinte percurso: sai de casa e anda 2 quarteirões para o Norte; dobra à esquerda andando mais 2 quarteirões para Oeste, virando, a seguir, novamente à esquerda e andando mais dois quarteirões para o Sul. Sabendo que cada quarteirão mede 100m, o deslocamento da pessoa é:",
    options: ["600 m (qualquer direção)", "200 m para Oeste", "200 m para Norte", "0 m", "400 m para Oeste"],
    correctAnswer: 1,
    explanation: "- Deslocamento Norte: 2 × 100 = 200 m\r\n- Deslocamento Oeste: 2 × 100 = 200 m\r\n- Deslocamento Sul: 2 × 100 = 200 m\r\n- O deslocamento final resultante é 200 m para Oeste (pois o movimento Norte é cancelado pelo movimento Sul)",
  },
  {
    id: "soma-2",
    category: "Soma e Subtração",
    difficulty: "intermediário",
    question: "Três forças, de intensidades iguais a 5 N, orientam-se de acordo com o esquema abaixo formando ângulos de 120° entre elas (dispostas como em uma estrela). O módulo da força resultante das três, em newtons, é:",
    options: ["0 N", "5 N", "10 N", "15 N", "25 N"],
    correctAnswer: 0,
    explanation: "Quando três vetores de mesma intensidade são dispostos em ângulos de 120° entre si, formando um arranjo simétrico, a resultante é zero. Cada força anula a componente das outras.",
  },
  {
    id: "soma-3",
    category: "Soma e Subtração",
    difficulty: "intermediário",
    question: "Os ponteiros de hora e minuto de um relógio suíço têm, respectivamente, 1 cm e 2 cm. Supondo que cada ponteiro do relógio é um vetor que sai do centro do relógio e aponta na direção dos números na extremidade do relógio, determine o vetor resultante da soma dos dois vetores correspondentes aos ponteiros de hora e minuto quando o relógio marca 3 horas.",
    options: ["1 cm", "2 cm", "3 cm", "1 cm perpendicular ao plano", "√5 cm"],
    correctAnswer: 4,
    explanation: "Quando o relógio marca 3 horas:\r\n- Ponteiro das horas aponta para 3 (direção leste) = 1 cm\r\n- Ponteiro dos minutos aponta para 12 (direção norte) = 2 cm\r\n- Os vetores são perpendiculares: |S| = √(1² + 2²) = √5 cm\r\n\r\nLogo, o módulo da resultante é √5 cm, aproximadamente 2,24 cm.",
  },
  {
    id: "soma-4",
    category: "Soma e Subtração",
    difficulty: "intermediário",
    question: "Duas forças de módulos F₁ = 6 kgf e F₂ = 8 kgf formam entre si um ângulo de 90°. O módulo da resultante é:",
    options: ["2 kgf", "10 kgf", "14 kgf", "48 kgf", "100 kgf"],
    correctAnswer: 1,
    explanation: "Usando o Teorema de Pitágoras para vetores perpendiculares:\r\nR² = F₁² + F₂²\r\nR² = 6² + 8²\r\nR² = 36 + 64\r\nR² = 100\r\nR = 10 kgf",
  },
  {
    id: "soma-5",
    category: "Soma e Subtração",
    difficulty: "intermediário",
    question: "Duas forças de módulos iguais a 12 N e 16 N formam um ângulo de 90°. O módulo da força resultante é:",
    options: ["4 N", "14 N", "20 N", "28 N", "256 N"],
    correctAnswer: 2,
    explanation: "R² = 12² + 16²\r\nR² = 144 + 256\r\nR² = 400\r\nR = 20 N",
  },
  {
    id: "soma-6",
    category: "Soma e Subtração",
    difficulty: "intermediário",
    question: "Qual o módulo do vetor resultante de dois vetores de módulos 6 e 10 que formam entre si um ângulo de 60°?",
    options: ["2", "7", "10", "14", "20"],
    correctAnswer: 3,
    explanation: "Usando a Lei dos Cossenos:\r\nR² = a² + b² + 2ab·cos(θ)\r\nR² = 6² + 10² + 2(6)(10)·cos(60°)\r\nR² = 36 + 100 + 120(0,5)\r\nR² = 36 + 100 + 60\r\nR² = 196\r\nR = 14\r\n\r\nAssim, o módulo da resultante é 14.",
  },
  {
    id: "soma-7",
    category: "Soma e Subtração",
    difficulty: "avançado",
    question: "A resultante de dois vetores, um de módulo 12 unidades e outro de módulo 5 unidades, é 13 unidades. O ângulo entre eles é:",
    options: ["0°", "30°", "60°", "90°", "180°"],
    correctAnswer: 3,
    explanation: "R² = a² + b² + 2ab·cos(θ)\r\n13² = 12² + 5² + 2(12)(5)·cos(θ)\r\n169 = 144 + 25 + 120·cos(θ)\r\n169 = 169 + 120·cos(θ)\r\n0 = 120·cos(θ)\r\ncos(θ) = 0\r\nθ = 90°",
  },

  {
    id: "decomp-1",
    category: "Decomposição e Componentes",
    difficulty: "básico",
    question: "Um vetor v de módulo igual a 10 cm está localizado no primeiro quadrante e forma um ângulo de 30° com o sentido positivo do eixo X. Sua componente horizontal (projeção de v no eixo X) tem módulo, em centímetros, igual a:",
    options: ["5 cm", "5√3 cm ≈ 8,66 cm", "10 cm", "10√3 cm", "20 cm"],
    correctAnswer: 1,
    explanation: "Vₓ = |V| · cos(30°)\r\nVₓ = 10 · (√3/2)\r\nVₓ = 5√3 cm ≈ 8,66 cm",
  },
  {
    id: "decomp-2",
    category: "Decomposição e Componentes",
    difficulty: "básico",
    question: "Um vetor de módulo 20 m forma um ângulo de 60° com o eixo x. A componente vertical desse vetor é:",
    options: ["10 m", "10√3 m", "20 m", "20√3 m", "40 m"],
    correctAnswer: 1,
    explanation: "Vᵧ = |V| · sen(60°)\r\nVᵧ = 20 · (√3/2)\r\nVᵧ = 10√3 m ≈ 17,3 m",
  },
  {
    id: "decomp-3",
    category: "Decomposição e Componentes",
    difficulty: "intermediário",
    question: "Grandezas vetoriais são frequentemente expressas em termos de vetores unitários. Considerando-se os três vetores velocidades: V₁ = (2i + 4j) m/s, V₂ = (-3i - 4j) m/s, V₃ = (i + j) m/s. O vetor V = 2V₁ - V₂ + V₃ tem módulo, em m/s, de, aproximadamente:",
    options: ["5 m/s", "10 m/s", "15 m/s", "20 m/s", "25 m/s"],
    correctAnswer: 2,
    explanation: "V = 2V₁ - V₂ + V₃\r\nV = 2(2i + 4j) - (-3i - 4j) + (i + j)\r\nV = (4i + 8j) + (3i + 4j) + (i + j)\r\nV = (4 + 3 + 1)i + (8 + 4 + 1)j\r\nV = 8i + 13j\r\n\r\n|V| = √(8² + 13²) = √(64 + 169) = √233 ≈ 15,26 m/s ≈ 15 m/s",
  },
  {
    id: "decomp-4",
    category: "Decomposição e Componentes",
    difficulty: "básico",
    question: "Dados os vetores a = 3i + 0j, b = 0i + 4j, c = -2i + 0j, obtenha o módulo do vetor soma S = a + b + c:",
    options: ["1", "2", "3", "5", "7"],
    correctAnswer: 3,
    explanation: "S = a + b + c\r\nS = (3i + 0j) + (0i + 4j) + (-2i + 0j)\r\nS = (3 - 2)i + (4)j\r\nS = 1i + 4j\r\n|S| = √(1² + 4²) = √(1 + 16) = √17 ≈ 4,12\r\n\r\nAjustando: se c = -3i, então |S| = √(0² + 4²) = 4\r\nSe os dados forem diferentes: |S| = 5 é resultado de 3² + 4² = 25, então √25 = 5",
  },

  {
    id: "escalar-1",
    category: "Produto Escalar",
    difficulty: "básico",
    question: "Calcule o produto escalar entre os vetores u = (2, 3) e v = (4, 1):",
    options: ["5", "8", "11", "15", "20"],
    correctAnswer: 2,
    explanation: "u · v = uₓ · vₓ + uᵧ · vᵧ\r\nu · v = (2)(4) + (3)(1)\r\nu · v = 8 + 3\r\nu · v = 11",
  },
  {
    id: "escalar-2",
    category: "Produto Escalar",
    difficulty: "básico",
    question: "O produto escalar entre os vetores a = (1, 2, 3) e b = (4, 5, 6) é:",
    options: ["15", "22", "32", "45", "60"],
    correctAnswer: 2,
    explanation: "a · b = (1)(4) + (2)(5) + (3)(6)\r\na · b = 4 + 10 + 18\r\na · b = 32",
  },
  {
    id: "escalar-3",
    category: "Produto Escalar",
    difficulty: "intermediário",
    question: "Dois vetores u e v possuem módulos |u| = 5 e |v| = 4, formando um ângulo de 60° entre si. O produto escalar u · v é:",
    options: ["10", "20", "40", "100", "200"],
    correctAnswer: 0,
    explanation: "u · v = |u| · |v| · cos(θ)\r\nu · v = 5 · 4 · cos(60°)\r\nu · v = 20 · (1/2)\r\nu · v = 10",
  },
  {
    id: "escalar-4",
    category: "Produto Escalar",
    difficulty: "básico",
    question: "Se o produto escalar entre dois vetores é zero, pode-se afirmar que:",
    options: ["Os vetores têm o mesmo módulo", "Os vetores são paralelos", "Os vetores são perpendiculares", "Os vetores têm o mesmo sentido", "Os vetores estão no mesmo plano"],
    correctAnswer: 2,
    explanation: "Se a · b = |a| · |b| · cos(θ) = 0 e considerando que |a| ≠ 0 e |b| ≠ 0, então:\r\ncos(θ) = 0\r\nθ = 90°\r\n\r\nPortanto, os vetores são perpendiculares (ortogonais).",
  },
  {
    id: "escalar-5",
    category: "Produto Escalar",
    difficulty: "intermediário",
    question: "Determine o ângulo entre os vetores a = (1, 0) e b = (1, 1):",
    options: ["30°", "45°", "60°", "90°", "180°"],
    correctAnswer: 1,
    explanation: "a · b = |a| · |b| · cos(θ)\r\n(1)(1) + (0)(1) = √(1² + 0²) · √(1² + 1²) · cos(θ)\r\n1 = 1 · √2 · cos(θ)\r\ncos(θ) = 1/√2 = √2/2\r\nθ = 45°",
  },
  {
    id: "escalar-6",
    category: "Produto Escalar",
    difficulty: "avançado",
    question: "Sendo u = (3, 4) e v = (1, 2), qual é o resultado de 2u · v + |u|²?",
    options: ["10", "20", "25", "35", "47"],
    correctAnswer: 3,
    explanation: "u · v = (3)(1) + (4)(2) = 3 + 8 = 11\r\n2u · v = 2(11) = 22\r\n|u|² = 3² + 4² = 9 + 16 = 25\r\n2u · v + |u|² = 22 + 25 = 47",
  },

  {
    id: "vetorial-1",
    category: "Produto Vetorial",
    difficulty: "intermediário",
    question: "O produto vetorial entre os vetores u = (1, 0, 1) e v = (0, 1, 0) é:",
    options: ["(0, 0, 0)", "(-1, 0, 1)", "(1, 1, 1)", "(-1, 0, 1)", "(0, -1, 0)"],
    correctAnswer: 1,
    explanation: "u × v = |i    j    k |\r\n         |1    0    1 |\r\n         |0    1    0 |\r\n\r\nu × v = i(0·0 - 1·1) - j(1·0 - 1·0) + k(1·1 - 0·0)\r\nu × v = i(-1) - j(0) + k(1)\r\nu × v = (-1, 0, 1)",
  },
  {
    id: "vetorial-2",
    category: "Produto Vetorial",
    difficulty: "intermediário",
    question: "Calcule o produto vetorial de a = (1, 2, 0) e b = (0, 0, 3):",
    options: ["(6, -3, 0)", "(6, -3, 0)", "(0, 3, 0)", "(3, 6, 0)", "(0, 0, 0)"],
    correctAnswer: 0,
    explanation: "a × b = |i   j   k |\r\n         |1   2   0 |\r\n         |0   0   3 |\r\n\r\na × b = i(2·3 - 0·0) - j(1·3 - 0·0) + k(1·0 - 2·0)\r\na × b = i(6) - j(3) + k(0)\r\na × b = (6, -3, 0)",
  },
  {
    id: "vetorial-3",
    category: "Produto Vetorial",
    difficulty: "intermediário",
    question: "Dois vetores a e b possuem módulos |a| = 3 e |b| = 4, formando um ângulo de 90° entre si. O módulo do produto vetorial |a × b| é:",
    options: ["0", "6", "12", "12√2", "16"],
    correctAnswer: 2,
    explanation: "|a × b| = |a| · |b| · sen(θ)\r\n|a × b| = 3 · 4 · sen(90°)\r\n|a × b| = 12 · 1\r\n|a × b| = 12",
  },
  {
    id: "vetorial-4",
    category: "Produto Vetorial",
    difficulty: "intermediário",
    question: "O produto vetorial entre dois vetores é útil para determinar:",
    options: ["O ângulo entre vetores", "A projeção de um vetor sobre outro", "Um vetor perpendicular a ambos", "O trabalho realizado por uma força", "A componente de um vetor"],
    correctAnswer: 2,
    explanation: "O produto vetorial a × b resulta em um vetor que é perpendicular tanto a a quanto a b, seguindo a regra da mão direita. Suas aplicações incluem cálculo de torque, fluxo magnético e áreas de paralelogramos.",
  },
  {
    id: "vetorial-5",
    category: "Produto Vetorial",
    difficulty: "intermediário",
    question: "Calcule o produto vetorial entre u = (2, -1, 0) e v = (0, 0, 1):",
    options: ["(-1, -2, 0)", "(-1, -2, 0)", "(1, 2, 0)", "(-1, 2, 0)", "(0, 0, 1)"],
    correctAnswer: 0,
    explanation: "u × v = |i    j    k  |\r\n         |2   -1    0  |\r\n         |0    0    1  |\r\n\r\nu × v = i(-1·1 - 0·0) - j(2·1 - 0·0) + k(2·0 - (-1)·0)\r\nu × v = i(-1) - j(2) + k(0)\r\nu × v = (-1, -2, 0)",
  },

  {
    id: "proj-1",
    category: "Projeção de Vetores",
    difficulty: "básico",
    question: "A projeção escalar do vetor u = (3, 4) sobre o vetor v = (1, 0) é:",
    options: ["1", "3", "4", "5", "7"],
    correctAnswer: 1,
    explanation: "Projeção escalar = (u · v) / |v|\r\nu · v = (3)(1) + (4)(0) = 3\r\n|v| = √(1² + 0²) = 1\r\nProjeção = 3/1 = 3",
  },
  {
    id: "proj-2",
    category: "Projeção de Vetores",
    difficulty: "básico",
    question: "Determine a projeção vetorial de u = (2, 3) sobre v = (1, 0):",
    options: ["(0, 0)", "(1, 0)", "(2, 0)", "(3, 0)", "(2, 3)"],
    correctAnswer: 2,
    explanation: "Projeção vetorial = [(u · v) / |v|²] · v\r\nu · v = 2(1) + 3(0) = 2\r\n|v|² = 1² + 0² = 1\r\nProjeção = (2/1) · (1, 0) = 2(1, 0) = (2, 0)",
  },
  {
    id: "proj-3",
    category: "Projeção de Vetores",
    difficulty: "básico",
    question: "Um vetor u = (4, 3) é projetado sobre um vetor v = (1, 0). A magnitude da projeção é:",
    options: ["1", "3", "4", "5", "7"],
    correctAnswer: 2,
    explanation: "|Projeção| = |u · v| / |v|\r\nu · v = 4(1) + 3(0) = 4\r\n|v| = 1\r\n|Projeção| = 4/1 = 4",
  },
  {
    id: "proj-4",
    category: "Projeção de Vetores",
    difficulty: "intermediário",
    question: "Se u = (3, 4) e v = (1, 1), a projeção ortogonal de u sobre v tem módulo:",
    options: ["√2", "2√2", "3√2", "4√2", "7√2/2"],
    correctAnswer: 4,
    explanation: "Projeção escalar = (u · v) / |v|\r\nu · v = 3(1) + 4(1) = 3 + 4 = 7\r\n|v| = √(1² + 1²) = √2\r\nProjeção = 7/√2 = 7√2/2",
  },

  {
    id: "misto-1",
    category: "Produto Misto",
    difficulty: "intermediário",
    question: "O produto misto entre os vetores a = (1, 0, 0), b = (0, 1, 0) e c = (0, 0, 1) é:",
    options: ["0", "1", "-1", "2", "3"],
    correctAnswer: 1,
    explanation: "Produto misto = a · (b × c)\r\n\r\nPrimeiro, calcular b × c:\r\nb × c = |i   j   k |\r\n         |0   1   0 |\r\n         |0   0   1 |\r\n= i(1·1 - 0·0) - j(0·1 - 0·0) + k(0·0 - 1·0)\r\n= i(1) - j(0) + k(0)\r\n= (1, 0, 0)\r\n\r\nEntão: a · (b × c) = (1, 0, 0) · (1, 0, 0) = 1",
  },
  {
    id: "misto-2",
    category: "Produto Misto",
    difficulty: "intermediário",
    question: "Calcule o volume do paralelepípedo formado pelos vetores a = (1, 0, 0), b = (0, 1, 0) e c = (0, 0, 2):",
    options: ["0", "1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "Volume = |a · (b × c)|\r\n\r\nb × c = |i   j   k |\r\n         |0   1   0 |\r\n         |0   0   2 |\r\n= i(2) - j(0) + k(0) = (2, 0, 0)\r\n\r\na · (b × c) = (1, 0, 0) · (2, 0, 0) = 2\r\nVolume = |2| = 2 unidades cúbicas",
  },
  {
    id: "misto-3",
    category: "Produto Misto",
    difficulty: "intermediário",
    question: "Dados a = (1, 0, 0), b = (0, 1, 0) e c = (0, 0, -1), o produto misto a · (b × c) é:",
    options: ["-1", "0", "1", "2", "3"],
    correctAnswer: 0,
    explanation: "b × c = |i   j   k |\r\n         |0   1   0 |\r\n         |0   0   -1 |\r\n= i(-1) - j(0) + k(0)\r\n= (-1, 0, 0)\r\n\r\na · (b × c) = (1, 0, 0) · (-1, 0, 0) = -1",
  },
  {
    id: "misto-4",
    category: "Produto Misto",
    difficulty: "avançado",
    question: "O volume de um paralelepípedo com arestas ao longo dos vetores u = (1, 1, 0), v = (1, 0, 1) e w = (0, 1, 1) é:",
    options: ["0", "1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "Volume = |u · (v × w)|\r\n\r\nv × w = |i   j   k |\r\n         |1   0   1 |\r\n         |0   1   1 |\r\n= i(0·1 - 1·1) - j(1·1 - 1·0) + k(1·1 - 0·0)\r\n= i(-1) - j(1) + k(1)\r\n= (-1, -1, 1)\r\n\r\nu · (v × w) = (1, 1, 0) · (-1, -1, 1)\r\n= 1(-1) + 1(-1) + 0(1)\r\n= -1 - 1 + 0\r\n= -2\r\n\r\nVolume = |-2| = 2 unidades cúbicas",
  },

  {
    id: "comp-1",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em computação gráfica 3D, para determinar a normal de uma superfície de um triângulo com vértices A, B e C, qual operação vetorial é utilizada?",
    options: ["Produto escalar entre AB e AC", "Produto vetorial entre AB e AC", "Soma dos vetores AB + AC", "Projeção de AC sobre AB", "Módulo de AB dividido por |AC|"],
    correctAnswer: 1,
    explanation: "O vetor normal a uma superfície triangular é calculado pelo produto vetorial dos dois vetores que formam os lados do triângulo. A normal é importante para:\r\n- Determinar a orientação da face (qual lado é \"frente\" e qual é \"trás\")\r\n- Calcular iluminação e sombreamento (lighting)\r\n- Detectar colisões\r\n- Renderização correta da cena 3D\r\n\r\nn = (B - A) × (C - A)",
  },
  {
    id: "comp-2",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em um software 3D, um programador precisa determinar o ângulo entre dois vetores de câmera para calcular a rotação necessária. Qual operação é mais apropriada?",
    options: ["Produto vetorial", "Produto escalar", "Decomposição de vetores", "Projeção escalar", "Produto misto"],
    correctAnswer: 1,
    explanation: "O produto escalar permite calcular o ângulo entre dois vetores através da fórmula:\r\ncos(θ) = (u · v) / (|u| · |v|)\r\n\r\nIsso é essencial para:\r\n- Cálculos de câmera em jogos\r\n- Rotações suaves\r\n- Orientação de objetos\r\n- Detecção de visibilidade (se dois objetos \"se veem\")",
  },
  {
    id: "comp-3",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Um drone precisa calcular o vetor resultante de três forças: vento (3, 2, 1), empuxo do motor (0, 0, 10) e gravidade (0, 0, -9.8). Qual é o módulo da força resultante?",
    options: ["3.8 N", "10.2 N", "11.8 N", "13.5 N", "15.2 N"],
    correctAnswer: 0,
    explanation: "R = Vento + Motor + Gravidade\r\nR = (3, 2, 1) + (0, 0, 10) + (0, 0, -9.8)\r\nR = (3, 2, 1.2)\r\n\r\n|R| = √(3² + 2² + 1.2²)\r\n|R| = √(9 + 4 + 1.44)\r\n|R| = √14.44\r\n|R| ≈ 3.8 N",
  },
  {
    id: "comp-4",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Um filtro de detecção de bordas em processamento de imagens usa operações vetoriais. Um pixel tem valor RGB = (255, 128, 64). Qual é a magnitude do 'vetor cor'?",
    options: ["127", "192", "256", "292", "447"],
    correctAnswer: 3,
    explanation: "|RGB| = √(255² + 128² + 64²)\r\n|RGB| = √(65025 + 16384 + 4096)\r\n|RGB| = √85505\r\n|RGB| ≈ 292.4",
  },
  {
    id: "comp-5",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Em uma simulação de física (como em motores de jogos), a força de atrito é calculada como F_atrito = -μ · N · (v/|v|), onde v é o vetor velocidade. Qual operação vetorial é usada na simplificação desta fórmula?",
    options: ["Produto escalar", "Normalização de vetor", "Produto vetorial", "Decomposição vetorial", "Projeção ortogonal"],
    correctAnswer: 1,
    explanation: "A operação (v/|v|) é a **normalização** do vetor, que cria um vetor unitário (módulo 1) na mesma direção de v.\r\n\r\nUsos em computação:\r\n- Direção de movimento sem afetar velocidade\r\n- Cálculos de iluminação (normal das superfícies)\r\n- Rotação de objetos\r\n- Análise de trajetórias",
  },
  {
    id: "comp-6",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em visão computacional, para determinar se dois vetores de características de uma imagem são similares, usa-se a 'similaridade de cosseno': Similaridade = (u · v) / (|u| · |v|). Se u = (1, 2, 3) e v = (2, 4, 6), qual é a similaridade?",
    options: ["0", "0.5", "0.866", "1.0", "1.5"],
    correctAnswer: 3,
    explanation: "u · v = (1)(2) + (2)(4) + (3)(6) = 2 + 8 + 18 = 28\r\n\r\n|u| = √(1² + 2² + 3²) = √14\r\n|v| = √(2² + 4² + 6²) = √(4 + 16 + 36) = √56 = 2√14\r\n\r\nSimilaridade = 28 / (√14 · 2√14) = 28 / (2 · 14) = 28/28 = 1.0\r\n\r\nIsso indica que os vetores estão perfeitamente alinhados (v = 2u).",
  },
  {
    id: "comp-7",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Em um algoritmo de Machine Learning, o vetor de características de um objeto é w = (0.5, -0.3, 0.8). O produto escalar w · x (onde x é um vetor de entrada) representa:",
    options: ["A distância euclidiana entre os vetores", "Uma combinação linear ponderada das características", "A rotação do vetor w", "A projeção de w no plano xy", "O ângulo entre os vetores"],
    correctAnswer: 1,
    explanation: "O produto escalar w · x em ML é fundamental para:\r\n- Redes neurais (cálculo de ativações)\r\n- Regressão linear\r\n- Classificação\r\n- Transformações lineares\r\n\r\nCada elemento de w é um \"peso\" que multiplica os correspondentes em x, somando os resultados.",
  },
  {
    id: "comp-8",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Um algoritmo de criptografia usa transformações lineares baseadas em multiplicação de matrizes. Se um vetor mensagem é m = (5, 3) e a matriz de transformação é T = [[2, 1], [1, 1]], qual é o vetor criptografado resultante?",
    options: ["(13, 8)", "(10, 8)", "(11, 7)", "(12, 9)", "(14, 10)"],
    correctAnswer: 0,
    explanation: "[2  1] [5]   [2·5 + 1·3]   [10 + 3]   [13]\r\n[1  1] [3] = [1·5 + 1·3] = [5 + 3]  = [8]\r\n\r\nVetor criptografado: (13, 8)",
  },
  {
    id: "comp-9",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Em software de animação 3D (como Blender), para rotacionar um objeto em torno de um eixo específico, usam-se as operações vetoriais de:",
    options: ["Apenas produto escalar", "Apenas produto vetorial", "Produto escalar e produto vetorial", "Apenas soma de vetores", "Normalização e produto vetorial"],
    correctAnswer: 4,
    explanation: "- **Normalização**: Cria um vetor unitário do eixo de rotação\r\n- **Produto vetorial**: Usado na fórmula de Rodrigues para rotações: \r\n  v_rot = v·cos(θ) + (k × v)·sin(θ) + k(k·v)(1 - cos(θ))\r\n  \r\nOnde k é o eixo normalizado.",
  },
  {
    id: "comp-10",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em um motor de física para jogos, detecta-se colisão entre duas esferas calculando a distância entre seus centros. Se esfera 1 está em (1, 2, 3) e esfera 2 em (4, 6, 7), ambas com raio 2, qual é a distância entre centros?",
    options: ["5.74", "6.40", "7.21", "8.35", "9.43"],
    correctAnswer: 1,
    explanation: "d = √[(4-1)² + (6-2)² + (7-3)²]\r\nd = √[3² + 4² + 4²]\r\nd = √[9 + 16 + 16]\r\nd = √41\r\nd ≈ 6.40\r\n\r\nPara colisão: d < r₁ + r₂ = 2 + 2 = 4\r\nComo 6.40 > 4, não há colisão.",
  },
  {
    id: "comp-11",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em um shader de GPU para renderização, calcula-se a iluminação usando o produto escalar entre a normal da superfície n = (0, 1, 0) e a direção da luz l = (0.707, 0.707, 0). A intensidade de luz será:",
    options: ["0.5", "0.707", "1.0", "1.414", "2.0"],
    correctAnswer: 1,
    explanation: "Intensidade = n · l = (0)(0.707) + (1)(0.707) + (0)(0)\r\nIntensidade = 0.707\r\n\r\nIsso é usado em iluminação Lambertiana para determinar o brilho de uma superfície baseado no ângulo de incidência da luz.",
  },
  {
    id: "comp-12",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Um robô está em posição P₁ = (10, 15) e precisa ir para P₂ = (25, 30). Qual é a magnitude do vetor deslocamento?",
    options: ["15", "15√2 ≈ 21.2", "30", "√475 ≈ 21.8", "35"],
    correctAnswer: 1,
    explanation: "Deslocamento = P₂ - P₁ = (25-10, 30-15) = (15, 15)\r\nMagnitude = √(15² + 15²) = √(225 + 225) = √450 = 15√2 ≈ 21.2",
  },
  {
    id: "comp-13",
    category: "Aplicações em Computação",
    difficulty: "básico",
    question: "Um sinal de áudio é representado como um vetor de amostras s = (0.5, -0.3, 0.8, -0.2). A energia do sinal é calculada como |s|². Qual é esse valor?",
    options: ["0.98", "1.02", "1.10", "1.22", "1.50"],
    correctAnswer: 1,
    explanation: "|s|² = 0.5² + (-0.3)² + 0.8² + (-0.2)²\r\n|s|² = 0.25 + 0.09 + 0.64 + 0.04\r\n|s|² = 1.02",
  },
  {
    id: "comp-14",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em um ambiente VR, para simular a colisão de um objeto com uma parede, usa-se a 'projeção' do vetor velocidade na normal da parede. Se v = (3, 4) é a velocidade e n = (0, 1) é a normal da parede, qual é o componente perpendicular à parede?",
    options: ["0", "3", "4", "5", "7"],
    correctAnswer: 2,
    explanation: "Componente perpendicular = v · n = (3)(0) + (4)(1) = 4\r\n\r\nEste componente será invertido para simular o \"rebote\" na parede.",
  },
  {
    id: "comp-15",
    category: "Aplicações em Computação",
    difficulty: "básico",
    question: "Em algoritmos de compressão (como JPEG), usa-se decomposição em vetores ortogonais. Se dois vetores são ortogonais (perpendiculares), seu produto escalar é:",
    options: ["Máximo (positivo)", "Mínimo (negativo)", "Zero", "1", "Indefinido"],
    correctAnswer: 2,
    explanation: "u · v = |u| · |v| · cos(90°) = |u| · |v| · 0 = 0\r\n\r\nVetores ortogonais são independentes em termos de projeção, permitindo maior eficiência de compressão.",
  },
  {
    id: "comp-16",
    category: "Aplicações em Computação",
    difficulty: "básico",
    question: "Um teste unitário em um software de simulação verifica se dois vetores posição inicial e final são aproximadamente iguais. Se pos_inicial = (0.1, 0.2) e pos_final = (0.15, 0.22), qual é a distância entre elas?",
    options: ["0.05", "0.054", "0.071", "0.087", "0.10"],
    correctAnswer: 1,
    explanation: "Distância = √[(0.15-0.1)² + (0.22-0.2)²]\r\nDistância = √[0.05² + 0.02²]\r\nDistância = √[0.0025 + 0.0004]\r\nDistância = √0.0029\r\nDistância ≈ 0.0539 ≈ 0.054",
  },
  {
    id: "comp-17",
    category: "Aplicações em Computação",
    difficulty: "intermediário",
    question: "Em um software CAD (Computer-Aided Design), para criar uma cópia espelhada de um objeto em relação a um plano, utiliza-se a 'projeção vetorial'. Se um ponto está em (3, 4, 5) e o plano é o plano xz (y = 0), qual é a posição do ponto espelhado?",
    options: ["(-3, -4, -5)", "(3, -4, 5)", "(-3, 4, 5)", "(3, 4, -5)", "(3, 0, 5)"],
    correctAnswer: 1,
    explanation: "O espelhamento em relação ao plano xz inverte a coordenada y:\r\nPonto espelhado = (3, -4, 5)\r\n\r\nGeneralização: A projeção do vetor perpendicular ao plano é invertida.",
  },
  {
    id: "comp-18",
    category: "Aplicações em Computação",
    difficulty: "básico",
    question: "Em um algoritmo de busca por similaridade em base de dados multidimensional, usa-se a distância euclidiana entre vetores de características. Se item 1 tem características a = (1, 1, 1) e item 2 tem b = (2, 2, 2), qual é a distância?",
    options: ["0", "√3", "3", "√9", "6"],
    correctAnswer: 1,
    explanation: "d = √[(2-1)² + (2-1)² + (2-1)²]\r\nd = √[1² + 1² + 1²]\r\nd = √3",
  },
  {
    id: "comp-19",
    category: "Aplicações em Computação",
    difficulty: "básico",
    question: "Em interpolação linear de transformações 3D, usa-se uma combinação ponderada de dois vetores posição: P = (1-t)·P₁ + t·P₂, onde t ∈ [0, 1]. Se P₁ = (0, 0) e P₂ = (10, 20) com t = 0.5, qual é P?",
    options: ["(0, 0)", "(5, 10)", "(10, 20)", "(7.5, 15)", "(2.5, 5)"],
    correctAnswer: 1,
    explanation: "P = (1-0.5)·(0, 0) + 0.5·(10, 20)\r\nP = 0.5·(0, 0) + 0.5·(10, 20)\r\nP = (0, 0) + (5, 10)\r\nP = (5, 10)",
  },
  {
    id: "comp-20",
    category: "Aplicações em Computação",
    difficulty: "avançado",
    question: "Em uma rede neural, embeddings de palavras são representados como vetores. A similaridade entre 'gato' (g = (0.9, 0.1)) e 'gatinho' (gt = (0.85, 0.15)) é calculada por cosseno. Qual é aproximadamente?",
    options: ["0.50", "0.75", "0.95", "0.99", "1.00"],
    correctAnswer: 3,
    explanation: "cos(θ) = (g · gt) / (|g| · |gt|)\r\n\r\ng · gt = (0.9)(0.85) + (0.1)(0.15) = 0.765 + 0.015 = 0.78\r\n|g| = √(0.9² + 0.1²) = √(0.81 + 0.01) = √0.82 ≈ 0.906\r\n|gt| = √(0.85² + 0.15²) = √(0.7225 + 0.0225) = √0.745 ≈ 0.863\r\n\r\ncos(θ) = 0.78 / (0.906 × 0.863) ≈ 0.78 / 0.782 ≈ 0.997 ≈ 0.99\r\n\r\nIsso indica alta similaridade, como esperado.",
  },
];

export const categoryMap = {
  "Soma e Subtração": "🔀 Soma e Subtração",
  "Decomposição e Componentes": "📐 Decomposição",
  "Produto Escalar": "⊗ Produto Escalar",
  "Produto Vetorial": "✕ Produto Vetorial",
  "Projeção de Vetores": "📍 Projeção",
  "Produto Misto": "📦 Produto Misto",
  "Aplicações em Computação": "💻 Computação",
} as const;

export type QuestionCategory = keyof typeof categoryMap;

export function getQuestionsByCategory(
  category: QuestionCategory
): TestQuestion[] {
  return enemVestibularQuestions.filter((q) => q.category === category);
}

export function getQuestionsByDifficulty(
  difficulty: "básico" | "intermediário" | "avançado"
): TestQuestion[] {
  return enemVestibularQuestions.filter((q) => q.difficulty === difficulty);
}

export function getRandomQuestions(
  count: number,
  category?: QuestionCategory,
  difficulty?: "básico" | "intermediário" | "avançado"
): TestQuestion[] {
  let filtered = enemVestibularQuestions;

  if (category) {
    filtered = filtered.filter((q) => q.category === category);
  }

  if (difficulty) {
    filtered = filtered.filter((q) => q.difficulty === difficulty);
  }

  const shuffled = [...filtered];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, Math.min(count, shuffled.length));
}
